export const data = [
    {key :1,
        img : "./abc.jpg",
        info :"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer",
    },
    {key :2,
        img : "./abc.jpg",
       info :"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer",
    },
    {key :3,
        img : "./abc.jpg",
       info :"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer",
    },
    {key :4,
        img : "./abc.jpg",
       info :"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer",
    },
    {key :5,
        img : "./abc.jpg",
       info :"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer",
    },
    {key :6,
        img : "./abc.jpg",
       info :"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer",
    },
    {key :7,
        img : "./abc.jpg",
       info :"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer",
    },
    {key :8,
        img : "./abc.jpg",
       info :"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer",
    },
    {key :9,
        img : "./abc.jpg",
       info :"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer",
    },
    

]