export const data = [
    {key :1,
        img : "./images/raj-desai.jpeg",
        name: "Raj Desai",
        pos: "Chair Person",
        insta: "https://www.instagram.com/rv_desai_/",
        linkedin: "https://www.linkedin.com/in/raj-desai-6a7a5721b/",
    },
    {key :2,
        img : "./images/pragya.jpeg",
        name: "Pragya Shukla",
        pos : "Vice Chairperson",
        insta: "https://www.instagram.com/praggyya__/",
        linkedin: "https://www.linkedin.com/in/pragya-s-5a5169209",
     },
    {key :3,
        img : "./images/sakshi-sharma.jpg",
        name: "Sakshi Sharma",
        pos: "Secretary",
        insta: "https://www.instagram.com/sakshi__2425/",
        linkedin: "https://www.linkedin.com/in/sakshi-sharma-068bb6207/",
     },
    {key :4,
        img : "./images/aditi.jpeg",
        name: "Aditi Shah",
        pos: "Event Manager",
        insta: "https://www.instagram.com/aditi_shah._/",
        linkedin: "https://www.linkedin.com/in/aditi-shah-187b271b6/",
     },
    {key :5,
        img : "./images/ankur.jpeg",
        name: "Ankur Kulkarni",
        pos: "Treasurer",
        insta: "https://www.instagram.com/ankur_orion/",
        linkedin: "https://www.linkedin.com/in/ankurkul95/",
     },
    {key :6,
        img : "./images/naman.jpeg",
        name: "Naman Agarwal",
        pos: "Sponsorship Head",
        insta: "https://www.instagram.com/__namanagarwal_/",
        linkedin: "https://www.linkedin.com/in/naman-agarwal-0867a3204/",
     },
    {key :7,
        img : "./images/rhea.jpeg",
        name: "Rhea Rajput",
        pos: "Publication Head",
        insta: "https://www.instagram.com/eupho.rhea/",
        linkedin: "https://www.linkedin.com/in/rhea-rajput/",
     },
    {key :8,
        img : "./images/deep.jpeg",
        name: "Deep Khasgiwal",
        pos: "Webmaster",
        insta: "https://www.instagram.com/deep.the.kid/",
        linkedin: "https://www.linkedin.com/in/deep-khasgiwala-4326ba252/",
     },
    {key :9,
        img : "./images/om-hinge.jpeg",
        name: "Om Hinge",
        pos: "Technical Head",
        insta: "https://www.instagram.com/om_ace_2635/",
        linkedin: "https://www.linkedin.com/in/om-hinge2635/",
     },
     {key :10,
        img : "./images/purvashi.jpeg",
        name: "Purvashi Shah",
        pos: "Event Coordinator",
        insta: "https://www.instagram.com/purvashi_shah/",
        linkedin: "https://www.linkedin.com/in/purvashi-shah-b95705227/",
     },

]